# Generated by Django 4.2.1 on 2023-08-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_users_fund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField()),
                ('email', models.TextField()),
                ('text', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='time')),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField()),
                ('receiver', models.TextField()),
                ('amount', models.IntegerField(default=0, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='time')),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField()),
                ('receiver', models.TextField()),
                ('amount', models.IntegerField(default=0, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='time')),
            ],
        ),
    ]
