# Generated by Django 4.2.1 on 2023-08-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_users_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='account',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
